# Form implementation generated from reading ui file 'Ui_SettingWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from common import get_resource_path


class Ui_SettingWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 495)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_frame.setStyleSheet("QFrame{\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "border:0px solid red;\n"
                                      "border-radius:30px\n"
                                      "}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(12)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_left = QtWidgets.QFrame(parent=self.main_frame)
        self.frame_left.setMinimumSize(QtCore.QSize(131, 495))
        self.frame_left.setMaximumSize(QtCore.QSize(131, 495))
        self.frame_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_12.setSpacing(36)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_left_head = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_left_head.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left_head.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left_head.setObjectName("frame_left_head")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_left_head)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_don_kone = QtWidgets.QWidget(parent=self.frame_left_head)
        self.widget_don_kone.setMinimumSize(QtCore.QSize(0, 32))
        self.widget_don_kone.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_don_kone.setStyleSheet("image: url(:/svg/Morikawa/01_Data/img/logo/443px.png);")
        self.widget_don_kone.setObjectName("widget_don_kone")
        self.horizontalLayout_17.addWidget(self.widget_don_kone)
        self.verticalLayout_12.addWidget(self.frame_left_head)
        self.frame_list = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_list.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_list.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_list.setObjectName("frame_list")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_list)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.listWidget_setting = QtWidgets.QListWidget(parent=self.frame_list)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.listWidget_setting.setFont(font)
        self.listWidget_setting.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.listWidget_setting.setStyleSheet("QListView {\n"
                                              "\n"
                                              "}\n"
                                              "QListView::item{\n"
                                              "background-color: transparent;\n"
                                              "color: rgb(184, 184, 184);\n"
                                              "padding:8px;\n"
                                              "padding-left:4px;\n"
                                              "margin-bottom:8px;\n"
                                              "}\n"
                                              "QListView::item:hover {\n"
                                              "border-radius:8px;\n"
                                              "background-color: rgb(245, 249, 254)\n"
                                              "}\n"
                                              "QListView::item:selected {\n"
                                              "background-color: rgb(235, 242, 255);\n"
                                              "color: rgb(12, 20, 36);\n"
                                              "border-radius:8px;\n"
                                              "}\n"
                                              "")
        self.listWidget_setting.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_setting.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_setting.setObjectName("listWidget_setting")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/setting/基本设置.svg')), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        item.setIcon(icon)
        self.listWidget_setting.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/setting/高级设置.svg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        item.setIcon(icon1)
        self.listWidget_setting.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/setting/其他设置.svg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        item.setIcon(icon2)
        self.listWidget_setting.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/setting/关于枫叶.svg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        item.setIcon(icon3)
        self.listWidget_setting.addItem(item)
        self.horizontalLayout_15.addWidget(self.listWidget_setting)
        self.verticalLayout_12.addWidget(self.frame_list)
        self.frame_left_bottom = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_left_bottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left_bottom.setObjectName("frame_left_bottom")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_left_bottom)
        self.horizontalLayout_16.setContentsMargins(12, 0, -1, 12)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_exit_setting = QtWidgets.QPushButton(parent=self.frame_left_bottom)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_exit_setting.setFont(font)
        self.pushButton_exit_setting.setStyleSheet("QPushButton {\n"
                                                   "color: rgb(160, 160, 160);\n"
                                                   "border:none;\n"
                                                   "text-align:left;\n"
                                                   "padding:10px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "QPushButton:hover {\n"
                                                   "color: rgb(120, 120, 120);\n"
                                                   "}\n"
                                                   "\n"
                                                   "QPushButton:pressed {\n"
                                                   "color: rgb(0, 0, 0);\n"
                                                   "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/setting/完成设置.svg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.pushButton_exit_setting.setIcon(icon4)
        self.pushButton_exit_setting.setObjectName("pushButton_exit_setting")
        self.horizontalLayout_16.addWidget(self.pushButton_exit_setting, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout_12.addWidget(self.frame_left_bottom)
        self.verticalLayout_12.setStretch(1, 2)
        self.verticalLayout_12.setStretch(2, 1)
        self.horizontalLayout_18.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(parent=self.main_frame)
        self.frame_right.setMinimumSize(QtCore.QSize(657, 495))
        self.frame_right.setMaximumSize(QtCore.QSize(657, 495))
        self.frame_right.setStyleSheet("QFrame{\n"
                                       "background-color: rgb(245, 245, 245);\n"
                                       "border:0px solid red;\n"
                                       "border-radius:30px\n"
                                       "}")
        self.frame_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_right)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_setting_1 = QtWidgets.QFrame(parent=self.page_1)
        self.frame_setting_1.setMinimumSize(QtCore.QSize(657, 495))
        self.frame_setting_1.setMaximumSize(QtCore.QSize(657, 495))
        self.frame_setting_1.setStyleSheet("")
        self.frame_setting_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_setting_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_setting_1.setObjectName("frame_setting_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_setting_1)
        self.verticalLayout_3.setContentsMargins(18, 12, 18, 24)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_setting_1 = QtWidgets.QLabel(parent=self.frame_setting_1)
        self.label_setting_1.setMinimumSize(QtCore.QSize(0, 72))
        self.label_setting_1.setMaximumSize(QtCore.QSize(16777215, 72))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.label_setting_1.setFont(font)
        self.label_setting_1.setObjectName("label_setting_1")
        self.verticalLayout_3.addWidget(self.label_setting_1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_24.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_24.setSpacing(8)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.checkBox_close_option = QtWidgets.QCheckBox(parent=self.frame_setting_1)
        self.checkBox_close_option.setMinimumSize(QtCore.QSize(0, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_close_option.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/buttom/img/buttom/F0_f-zero-key.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.checkBox_close_option.setIcon(icon5)
        self.checkBox_close_option.setObjectName("checkBox_close_option")
        self.horizontalLayout_24.addWidget(self.checkBox_close_option)
        self.horizontalLayout_24.setStretch(0, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_23.setSpacing(8)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_sound = QtWidgets.QCheckBox(parent=self.frame_setting_1)
        self.checkBox_sound.setMinimumSize(QtCore.QSize(0, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_sound.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/buttom/img/buttom/F1_f-one-key.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.checkBox_sound.setIcon(icon6)
        self.checkBox_sound.setObjectName("checkBox_sound")
        self.horizontalLayout_23.addWidget(self.checkBox_sound)
        self.pushButton_test_sound = QtWidgets.QPushButton(parent=self.frame_setting_1)
        self.pushButton_test_sound.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_test_sound.setSizeIncrement(QtCore.QSize(40, 40))
        self.pushButton_test_sound.setBaseSize(QtCore.QSize(40, 40))
        self.pushButton_test_sound.setStyleSheet("color: rgb(199, 199, 199);\n"
                                                 "border:none;")
        self.pushButton_test_sound.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/setting/播放测试.svg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.pushButton_test_sound.setIcon(icon7)
        self.pushButton_test_sound.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_test_sound.setObjectName("pushButton_test_sound")
        self.horizontalLayout_23.addWidget(self.pushButton_test_sound)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem1)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 1)
        self.horizontalLayout_23.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_net_time = QtWidgets.QCheckBox(parent=self.frame_setting_1)
        self.checkBox_net_time.setMinimumSize(QtCore.QSize(0, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_net_time.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/buttom/img/buttom/F2_f-two-key.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.checkBox_net_time.setIcon(icon8)
        self.checkBox_net_time.setObjectName("checkBox_net_time")
        self.horizontalLayout_6.addWidget(self.checkBox_net_time)
        self.horizontalLayout_6.setStretch(0, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_updata = QtWidgets.QCheckBox(parent=self.frame_setting_1)
        self.checkBox_updata.setMinimumSize(QtCore.QSize(0, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_updata.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/buttom/img/buttom/F4_f-four-key.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.checkBox_updata.setIcon(icon9)
        self.checkBox_updata.setObjectName("checkBox_updata")
        self.horizontalLayout_5.addWidget(self.checkBox_updata)
        self.horizontalLayout_5.setStretch(0, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 2)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.setStretch(5, 2)
        self.verticalLayout_3.setStretch(6, 1)
        self.verticalLayout_3.setStretch(7, 2)
        self.verticalLayout_3.setStretch(8, 5)
        self.verticalLayout.addWidget(self.frame_setting_1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_setting_2 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_setting_2.setMinimumSize(QtCore.QSize(657, 495))
        self.frame_setting_2.setMaximumSize(QtCore.QSize(657, 495))
        self.frame_setting_2.setStyleSheet("")
        self.frame_setting_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_setting_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_setting_2.setObjectName("frame_setting_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_setting_2)
        self.verticalLayout_4.setContentsMargins(18, 12, 18, 24)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_setting_2 = QtWidgets.QLabel(parent=self.frame_setting_2)
        self.label_setting_2.setMinimumSize(QtCore.QSize(0, 72))
        self.label_setting_2.setMaximumSize(QtCore.QSize(16777215, 72))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.label_setting_2.setFont(font)
        self.label_setting_2.setObjectName("label_setting_2")
        self.verticalLayout_4.addWidget(self.label_setting_2)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout_25.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_25.setSpacing(8)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_language = QtWidgets.QLabel(parent=self.frame_setting_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_language.setFont(font)
        self.label_language.setObjectName("label_language")
        self.horizontalLayout_25.addWidget(self.label_language)
        self.comboBox_language = QtWidgets.QComboBox(parent=self.frame_setting_2)
        self.comboBox_language.setMinimumSize(QtCore.QSize(106, 27))
        self.comboBox_language.setMaximumSize(QtCore.QSize(106, 27))
        self.comboBox_language.setStyleSheet("QComboBox {\n"
                                             "border: 1px solid #ccc;\n"
                                             "padding: 2px;\n"
                                             "font-family: \'Microsoft YaHei\', sans-serif;\n"
                                             "font-size: 14px;\n"
                                             "width: 120px;\n"
                                             "}\n"
                                             "QComboBox:hover {\n"
                                             "border-color: #888;\n"
                                             "}\n"
                                             "QComboBox QAbstractItemView {\n"
                                             "border-radius: 0px;\n"
                                             "background-color: white;\n"
                                             "selection-background-color: #ddd;\n"
                                             "}")
        self.comboBox_language.setObjectName("comboBox_language")
        self.comboBox_language.addItem("")
        self.comboBox_language.addItem("")
        self.comboBox_language.addItem("")
        self.horizontalLayout_25.addWidget(self.comboBox_language)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem5)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 1)
        self.horizontalLayout_25.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_26.setSpacing(8)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)

        self.label_timestep = QtWidgets.QLabel(parent=self.frame_setting_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timestep.setFont(font)
        self.label_timestep.setObjectName("label_timestep")
        self.horizontalLayout_26.addWidget(self.label_timestep)
        self.spinBox_timestep = QtWidgets.QSpinBox(parent=self.frame_setting_2)
        self.spinBox_timestep.setMinimumSize(QtCore.QSize(106, 27))
        self.spinBox_timestep.setMaximumSize(QtCore.QSize(106, 27))
        self.spinBox_timestep.setStyleSheet("QSpinBox {\n"
                                            "    border: 1px solid #ccc;\n"
                                            "    padding: 2px 20px 2px 4px;\n"
                                            "    font-family: \'Microsoft YaHei\', sans-serif;\n"
                                            "    font-size: 14px;\n"
                                            "    width: 120px;\n"
                                            "}\n"
                                            "\n"
                                            "QSpinBox:hover {\n"
                                            "    border-color: #888;\n"
                                            "}")
        self.spinBox_timestep.setObjectName("spinBox_timestep")
        self.horizontalLayout_26.addWidget(self.spinBox_timestep)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem7)
        self.horizontalLayout_26.setStretch(0, 1)
        self.horizontalLayout_26.setStretch(1, 1)
        self.horizontalLayout_26.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)

        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 2)
        self.verticalLayout_4.setStretch(4, 1)
        self.verticalLayout_4.setStretch(5, 2)
        self.verticalLayout_4.setStretch(6, 1)
        self.verticalLayout_4.setStretch(7, 2)
        self.verticalLayout_4.setStretch(8, 3)
        self.verticalLayout_2.addWidget(self.frame_setting_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_setting_3 = QtWidgets.QFrame(parent=self.page_3)
        self.frame_setting_3.setMinimumSize(QtCore.QSize(657, 495))
        self.frame_setting_3.setMaximumSize(QtCore.QSize(657, 495))
        self.frame_setting_3.setStyleSheet("")
        self.frame_setting_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_setting_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_setting_3.setObjectName("frame_setting_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_setting_3)
        self.verticalLayout_5.setContentsMargins(18, 12, 18, 24)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_setting_3 = QtWidgets.QLabel(parent=self.frame_setting_3)
        self.label_setting_3.setMinimumSize(QtCore.QSize(0, 72))
        self.label_setting_3.setMaximumSize(QtCore.QSize(16777215, 72))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.label_setting_3.setFont(font)
        self.label_setting_3.setObjectName("label_setting_3")
        self.verticalLayout_5.addWidget(self.label_setting_3)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout_27.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_27.setSpacing(8)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_28.setSpacing(8)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_9.setSpacing(8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(220, -1, -1, -1)
        self.horizontalLayout_10.setSpacing(8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 2)
        self.verticalLayout_5.setStretch(4, 1)
        self.verticalLayout_5.setStretch(5, 2)
        self.verticalLayout_5.setStretch(6, 1)
        self.verticalLayout_5.setStretch(7, 2)
        self.verticalLayout_5.setStretch(8, 3)
        self.verticalLayout_7.addWidget(self.frame_setting_3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_setting_4 = QtWidgets.QFrame(parent=self.page_4)
        self.frame_setting_4.setMinimumSize(QtCore.QSize(657, 495))
        self.frame_setting_4.setMaximumSize(QtCore.QSize(657, 495))
        self.frame_setting_4.setStyleSheet("")
        self.frame_setting_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_setting_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_setting_4.setObjectName("frame_setting_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_setting_4)
        self.verticalLayout_6.setContentsMargins(18, 12, 18, 24)
        self.verticalLayout_6.setSpacing(12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_setting_4 = QtWidgets.QLabel(parent=self.frame_setting_4)
        self.label_setting_4.setMinimumSize(QtCore.QSize(0, 72))
        self.label_setting_4.setMaximumSize(QtCore.QSize(16777215, 72))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.label_setting_4.setFont(font)
        self.label_setting_4.setObjectName("label_setting_4")
        self.verticalLayout_6.addWidget(self.label_setting_4)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(0, 6, -1, 6)
        self.horizontalLayout_30.setSpacing(8)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.pushButton_logo = QtWidgets.QPushButton(parent=self.frame_setting_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logo.sizePolicy().hasHeightForWidth())
        self.pushButton_logo.setSizePolicy(sizePolicy)
        self.pushButton_logo.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_logo.setSizeIncrement(QtCore.QSize(80, 80))
        self.pushButton_logo.setBaseSize(QtCore.QSize(80, 80))
        self.pushButton_logo.setStyleSheet("color: rgb(199, 199, 199);\n"
                                           "border:none;")
        self.pushButton_logo.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/setting/logo.png')), QtGui.QIcon.Mode.Normal,
                         QtGui.QIcon.State.Off)
        self.pushButton_logo.setIcon(icon10)
        self.pushButton_logo.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_logo.setObjectName("pushButton_logo")
        self.horizontalLayout_30.addWidget(self.pushButton_logo)
        self.horizontalLayout_30.setStretch(0, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_11.setSpacing(8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.label = QtWidgets.QLabel(parent=self.frame_setting_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.label_version = QtWidgets.QLabel(parent=self.frame_setting_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_version.setFont(font)
        self.label_version.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_11.addWidget(self.label_version)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 1)
        self.horizontalLayout_11.setStretch(2, 1)
        self.horizontalLayout_11.setStretch(3, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(0, -1, 6, -1)
        self.horizontalLayout_13.setSpacing(8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem16)
        self.pushButton_check_updata = QtWidgets.QPushButton(parent=self.frame_setting_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_check_updata.sizePolicy().hasHeightForWidth())
        self.pushButton_check_updata.setSizePolicy(sizePolicy)
        self.pushButton_check_updata.setMinimumSize(QtCore.QSize(88, 32))
        self.pushButton_check_updata.setMaximumSize(QtCore.QSize(88, 32))
        self.pushButton_check_updata.setSizeIncrement(QtCore.QSize(80, 80))
        self.pushButton_check_updata.setBaseSize(QtCore.QSize(80, 80))
        self.pushButton_check_updata.setStyleSheet("QPushButton {\n"
                                                   "    background-color: rgba(140, 120, 250, 180);\n"
                                                   "    color: white;\n"
                                                   "    border: none;\n"
                                                   "    border-radius: 6px;\n"
                                                   "    font-family: \'Microsoft YaHei\';\n"
                                                   "    font-size: 14px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "QPushButton:hover {\n"
                                                   "    background-color: rgb(140, 120, 255);\n"
                                                   "}\n"
                                                   "\n"
                                                   "QPushButton:pressed {\n"
                                                   "    background-color: rgb(140, 100, 255);\n"
                                                   "}")
        self.pushButton_check_updata.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_check_updata.setObjectName("pushButton_check_updata")
        self.horizontalLayout_13.addWidget(self.pushButton_check_updata)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem17)
        self.horizontalLayout_13.setStretch(0, 3)
        self.horizontalLayout_13.setStretch(1, 1)
        self.horizontalLayout_13.setStretch(2, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, -1, 12, -1)
        self.horizontalLayout_14.setSpacing(8)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_setting_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.pushButton_help = QtWidgets.QPushButton(parent=self.frame_setting_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_help.sizePolicy().hasHeightForWidth())
        self.pushButton_help.setSizePolicy(sizePolicy)
        self.pushButton_help.setMinimumSize(QtCore.QSize(88, 32))
        self.pushButton_help.setMaximumSize(QtCore.QSize(88, 32))
        self.pushButton_help.setSizeIncrement(QtCore.QSize(80, 80))
        self.pushButton_help.setBaseSize(QtCore.QSize(80, 80))
        self.pushButton_help.setStyleSheet("QPushButton {\n"
                                           "    background-color: rgba(140, 120, 250, 180);\n"
                                           "    color: white;\n"
                                           "    border: none;\n"
                                           "    border-radius: 6px;\n"
                                           "    font-family: \'Microsoft YaHei\';\n"
                                           "    font-size: 14px;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: rgb(140, 120, 255);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed {\n"
                                           "    background-color: rgb(140, 100, 255);\n"
                                           "}")
        self.pushButton_help.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_help.setObjectName("pushButton_help")
        self.horizontalLayout_14.addWidget(self.pushButton_help)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem19)
        self.horizontalLayout_14.setStretch(0, 2)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(3, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem20)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_12.setSpacing(8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem21)
        self.label_copy_right = QtWidgets.QLabel(parent=self.frame_setting_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_copy_right.setFont(font)
        self.label_copy_right.setStyleSheet("color:rgb(160, 160, 160)")
        self.label_copy_right.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_copy_right.setObjectName("label_copy_right")
        self.horizontalLayout_12.addWidget(self.label_copy_right)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem22)
        self.horizontalLayout_12.setStretch(0, 2)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(2, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 3)
        self.verticalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.setStretch(3, 1)
        self.verticalLayout_6.setStretch(5, 5)
        self.verticalLayout_8.addWidget(self.frame_setting_4)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_13.addWidget(self.stackedWidget)
        self.horizontalLayout_18.addWidget(self.frame_right)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 5)
        self.horizontalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.listWidget_setting.setCurrentRow(-1)
        self.stackedWidget.setCurrentIndex(0)
        self.listWidget_setting.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget_setting.isSortingEnabled()
        self.listWidget_setting.setSortingEnabled(False)
        item = self.listWidget_setting.item(0)
        item.setText(_translate("MainWindow", "基本设置"))
        item = self.listWidget_setting.item(1)
        item.setText(_translate("MainWindow", "高级设置"))
        item = self.listWidget_setting.item(2)
        item.setText(_translate("MainWindow", "其他设置"))
        item = self.listWidget_setting.item(3)
        item.setText(_translate("MainWindow", "关于枫叶"))
        self.listWidget_setting.setSortingEnabled(__sortingEnabled)
        self.pushButton_exit_setting.setText(_translate("MainWindow", "完成设置"))
        self.label_setting_1.setText(_translate("MainWindow", "基本设置"))
        self.checkBox_close_option.setText(_translate("MainWindow", "点击关闭键最小化到托盘"))
        self.checkBox_sound.setText(_translate("MainWindow", "信息发送出错时播放提示音"))
        self.checkBox_net_time.setText(_translate("MainWindow", "全局使用网络授时（会员专享）"))
        self.checkBox_updata.setText(_translate("MainWindow", "启动时自动检查更新"))
        self.label_setting_2.setText(_translate("MainWindow", "高级设置"))
        self.label_language.setText(_translate("MainWindow", "PC客户端微信语言"))
        self.comboBox_language.setItemText(0, _translate("MainWindow", "简体中文"))
        self.comboBox_language.setItemText(1, _translate("MainWindow", "繁体中文"))
        self.comboBox_language.setItemText(2, _translate("MainWindow", "English"))
        self.label_timestep.setText(_translate("MainWindow", "添加任务自增分钟"))
        self.label_setting_3.setText(_translate("MainWindow", "其他设置"))
        self.label_setting_4.setText(_translate("MainWindow", "关于枫叶"))
        self.label.setText(_translate("MainWindow", "版本信息"))
        self.label_version.setText(_translate("MainWindow", "Null"))
        self.pushButton_check_updata.setText(_translate("MainWindow", "检查更新"))
        self.label_4.setText(_translate("MainWindow", "枫叶帮助"))
        self.pushButton_help.setText(_translate("MainWindow", "查看帮助"))
        self.label_copy_right.setText(_translate("MainWindow", "LeafAuto © 2024 Yangshengzhou All Rights Reserved"))
